SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	idcompte		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (idcompte),
	UNIQUE (pseudo)
);

CREATE TABLE velo (
	id_velo			INT				GENERATED BY DEFAULT AS IDENTITY,
	typevelo		VARCHAR(50)		NOT NULL,
	PRIMARY KEY (id_velo)
);


CREATE TABLE benevole (
	matricule_b			INT				GENERATED BY DEFAULT AS IDENTITY,
	nom              	VARCHAR (50) 	NOT NULL ,
    prenom          	VARCHAR (50) 	NOT NULL ,
    adresse          	VARCHAR (50) 	NOT NULL ,
    email            	VARCHAR (50) 	NOT NULL ,
    poste_souhaite   	TEXT 			NOT NULL ,
    permis_conduire  	BOOLEAN ,
    date_naissance   	DATE			NOT NULL ,
    type_benevole		INT				NOT NULL ,
	PRIMARY KEY (matricule_b)
);


CREATE TABLE dossard(
    numero_dossard 	INT 	NOT NULL ,
	PRIMARY KEY (numero_dossard)
);

CREATE TABLE equipe (	
	id_equipe 		INT				GENERATED BY DEFAULT AS IDENTITY, 
	nom_equipe		VARCHAR(50)		NOT NULL ,
	frais_paye     	INT 			NOT NULL ,
    numero_dossard 	INT 			NOT NULL ,
	PRIMARY KEY (id_equipe),
	FOREIGN KEY (numero_dossard) REFERENCES dossard(numero_dossard)
);
	
CREATE TABLE participant (
	matricule_p					INT				GENERATED BY DEFAULT AS IDENTITY,
	nom                  		VARCHAR (50) 	NOT NULL ,
    prenom                    	VARCHAR (50) 	NOT NULL ,
    date_naiss                	VARCHAR 		NOT NULL ,
    telephone                 	INT 			NOT NULL ,
    email                      	VARCHAR (50) 	NOT NULL ,
    adresse                    	VARCHAR (50) 	NOT NULL ,
    attestation_medical_pieds 	BOOLEAN  ,
    attestation_medical_velo  	BOOLEAN  ,
    attestation_medical_canoe 	BOOLEAN  ,
    frais_paye                	BOOLEAN  ,
    repas_supplementaire      	INT ,
    id_equipe                 	INT ,
    id_equipe_etre_coequipier 	INT ,
    id_velo                   	INT ,
	PRIMARY KEY (matricule_p),
 	FOREIGN KEY (id_equipe) REFERENCES equipe(id_equipe) ,
 	FOREIGN KEY (id_equipe_etre_coequipier)	REFERENCES equipe (id_equipe),
	FOREIGN KEY (id_velo) REFERENCES velo (id_velo)
);


CREATE TABLE type_course (	
	code 			INT				GENERATED BY DEFAULT AS IDENTITY, 
	libelle   		VARCHAR (50) 	NOT NULL ,
    id_equipe 		INT 			NOT NULL ,
	PRIMARY KEY (code),
 	FOREIGN KEY (id_equipe) REFERENCES equipe (id_equipe)
);

CREATE TABLE course (
	id_course    		INT				GENERATED BY DEFAULT AS IDENTITY,
	heure_depart 		Time 			NOT NULL ,
    lieu_depart  		VARCHAR (50) 	NOT NULL ,
    lieu_arrivee 		VARCHAR (50) 	NOT NULL ,
    parcours     		VARCHAR (50) 	NOT NULL ,
    code         		INT 			NOT NULL ,
	PRIMARY KEY (id_course),
	FOREIGN KEY (code) REFERENCES type_course (code)
);


CREATE TABLE poste (
	id_poste				INT				NOT NULL,
	nom_poste            	VARCHAR (50) 	NOT NULL ,
    description_poste     	VARCHAR (50) 	NOT NULL ,
    horaires_poste        	TIME 			NOT NULL ,
    personnel_poste      	INT 			NOT NULL ,
    localisation_poste    	TEXT 			NOT NULL ,
    Equipement_necessaire 	TEXT 			NOT NULL ,
    id_course             	INT 			NOT NULL ,
	PRIMARY KEY (id_poste),
	FOREIGN KEY (id_course) REFERENCES course(id_course)
);


CREATE TABLE etre_affecte(
    matricule_b 	INT 	NOT NULL ,
    id_poste    	INT 	NOT NULL ,
	PRIMARY KEY (matricule_b, id_poste) ,
	FOREIGN KEY (matricule_b)	REFERENCES benevole (matricule_b) ,
	FOREIGN KEY (id_poste)	REFERENCES poste(id_poste)
);


-- Vues

--CREATE VIEW v_compte_avec_roles AS
--	SELECT c.*, ARRAY_AGG( r.role ) AS roles
--	FROM compte c 
--	LEFT JOIN ROLE r ON c.idcompte = r.idcompte
--	GROUP BY c.idcompte;

